/**
 * Translation Service Abstraction
 *
 * This module provides a clean integration point for connecting a real
 * translation provider to the platform.
 *
 * CURRENT STATUS: Stub — returns empty strings for non-source languages.
 * Admin fills translations manually via the form.
 *
 * TO CONNECT A REAL PROVIDER:
 *   1. Implement the body of `callTranslationProvider()` below
 *   2. Examples:
 *      - Supabase Edge Function calling OpenAI GPT-4o
 *      - DeepL API (https://www.deepl.com/docs-api)
 *      - Google Cloud Translation API
 *   3. Change `TRANSLATION_PROVIDER_CONNECTED = true`
 */

export type SupportedLang = "ru" | "uz" | "en";

export type TranslationStatus =
  | "original"        // the source language — entered by admin
  | "auto_translated" // generated by translation provider
  | "reviewed"        // auto-translated and manually checked/edited
  | "missing";        // not yet filled

export interface MeetingTranslationDraft {
  title_ru: string;
  title_uz: string;
  title_en: string;
  status_ru: TranslationStatus;
  status_uz: TranslationStatus;
  status_en: TranslationStatus;
  providerConnected: boolean;
}

// ----------------------------------------------------------------
// INTEGRATION POINT: set to true when provider is connected
// ----------------------------------------------------------------
const TRANSLATION_PROVIDER_CONNECTED = false;

/**
 * Call the actual translation provider.
 * Replace the body of this function to connect a real service.
 */
async function callTranslationProvider(
  _text: string,
  _from: SupportedLang,
  _to: SupportedLang
): Promise<string> {
  // Example — Supabase Edge Function:
  // const { data: { session } } = await supabase.auth.getSession();
  // const resp = await fetch(`${SUPABASE_URL}/functions/v1/translate`, {
  //   method: "POST",
  //   headers: { Authorization: `Bearer ${session?.access_token}`, "Content-Type": "application/json" },
  //   body: JSON.stringify({ text: _text, from: _from, to: _to }),
  // });
  // const json = await resp.json();
  // return json.translated as string;

  // Example — DeepL direct:
  // const targetLang = _to === "uz" ? "UK" : _to.toUpperCase(); // closest available
  // const resp = await fetch("https://api-free.deepl.com/v2/translate", { ... });
  // return json.translations[0].text;

  throw new Error("Translation provider not connected");
}

/**
 * Generate translation drafts for a meeting title.
 *
 * If TRANSLATION_PROVIDER_CONNECTED is false:
 *   - Source language field gets the original text (status: "original")
 *   - Other fields remain empty (status: "missing")
 *   - Admin fills them manually
 *
 * If TRANSLATION_PROVIDER_CONNECTED is true:
 *   - All non-source fields are auto-translated (status: "auto_translated")
 *   - Admin can review/edit before saving
 */
export async function generateMeetingTranslations(
  sourceLang: SupportedLang,
  title: string
): Promise<MeetingTranslationDraft> {
  const draft: MeetingTranslationDraft = {
    title_ru: sourceLang === "ru" ? title : "",
    title_uz: sourceLang === "uz" ? title : "",
    title_en: sourceLang === "en" ? title : "",
    status_ru: sourceLang === "ru" ? "original" : "missing",
    status_uz: sourceLang === "uz" ? "original" : "missing",
    status_en: sourceLang === "en" ? "original" : "missing",
    providerConnected: TRANSLATION_PROVIDER_CONNECTED,
  };

  if (!TRANSLATION_PROVIDER_CONNECTED) {
    return draft;
  }

  const targets: SupportedLang[] = ["ru", "uz", "en"];
  for (const targetLang of targets) {
    if (targetLang === sourceLang) continue;
    try {
      const translated = await callTranslationProvider(title, sourceLang, targetLang);
      draft[`title_${targetLang}`] = translated;
      draft[`status_${targetLang}`] = "auto_translated";
    } catch (err) {
      console.error(`Translation to ${targetLang} failed:`, err);
      // Leave as empty / missing on error
    }
  }

  return draft;
}

/** Human-readable label for a translation status */
export function translationStatusLabel(status: TranslationStatus): string {
  switch (status) {
    case "original":        return "●";
    case "auto_translated": return "✦";
    case "reviewed":        return "✓";
    case "missing":         return "○";
  }
}

/** Color for translation status badge */
export function translationStatusColor(status: TranslationStatus): string {
  switch (status) {
    case "original":        return "#059669"; // green
    case "auto_translated": return "#7C3AED"; // purple
    case "reviewed":        return "#2563EB"; // blue
    case "missing":         return "#D1D5DB"; // gray
  }
}
