/**
 * Translation Service
 *
 * Calls the Supabase Edge Function `translate-text` which uses OpenAI
 * with a Smart Translation Router to translate board meeting / task content
 * into RU, UZ (Cyrillic), and EN.
 *
 * API key is never exposed to the frontend — it lives in Supabase secrets.
 *
 * To set the secret:
 *   supabase secrets set OPENAI_API_KEY=sk-...
 *
 * To deploy the function:
 *   supabase functions deploy translate-text --no-verify-jwt
 */

import { supabase, supabaseAnonKey } from "./supabaseClient";

export type SupportedLang = "ru" | "uz" | "en";

export type TranslationStatus =
  | "original"        // entered by user in source language
  | "auto_translated" // generated by OpenAI
  | "reviewed"        // auto-translated and manually checked/edited
  | "missing";        // not yet filled

export interface MeetingTranslationDraft {
  title_ru: string;
  title_uz: string;
  title_en: string;
  status_ru: TranslationStatus;
  status_uz: TranslationStatus;
  status_en: TranslationStatus;
  providerConnected: boolean;
}

export interface TaskTranslationDraft {
  title_ru: string;
  title_uz: string;
  title_en: string;
  description_ru: string;
  description_uz: string;
  description_en: string;
  status_ru: TranslationStatus;
  status_uz: TranslationStatus;
  status_en: TranslationStatus;
  providerConnected: boolean;
}

// ─── Internal: call the Edge Function ────────────────────────────────────────

interface EdgeFunctionLangResult {
  title?: string;
  description?: string;
  presenter?: string;
}

interface EdgeFunctionResponse {
  ru: EdgeFunctionLangResult;
  uz: EdgeFunctionLangResult;
  en: EdgeFunctionLangResult;
  meta: {
    model_used: string;
    source_language: string;
    auto_translated_languages: string[];
    retried_for_cyrillic?: boolean;
  };
}

async function callTranslateTextFunction(payload: {
  source_language: SupportedLang;
  entity_type: "board_meeting" | "task" | "agenda_item";
  fields: { title?: string; description?: string; presenter?: string };
}): Promise<EdgeFunctionResponse> {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) throw new Error("Not authenticated");

  const url = `${import.meta.env.VITE_SUPABASE_URL as string}/functions/v1/translate-text`;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${session.access_token}`,
      "apikey": supabaseAnonKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  const result = await res.json();

  if (!res.ok) {
    throw new Error(result.error || `Translation service error (HTTP ${res.status})`);
  }

  return result as EdgeFunctionResponse;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate translation drafts for a meeting title.
 * Calls the Edge Function; throws on error so the caller can display a message.
 */
export async function generateMeetingTranslations(
  sourceLang: SupportedLang,
  title: string
): Promise<MeetingTranslationDraft> {
  const result = await callTranslateTextFunction({
    source_language: sourceLang,
    entity_type: "board_meeting",
    fields: { title: title.trim() },
  });

  return {
    title_ru: result.ru.title ?? "",
    title_uz: result.uz.title ?? "",
    title_en: result.en.title ?? "",
    status_ru: sourceLang === "ru" ? "original" : "auto_translated",
    status_uz: sourceLang === "uz" ? "original" : "auto_translated",
    status_en: sourceLang === "en" ? "original" : "auto_translated",
    providerConnected: true,
  };
}

/**
 * Generate translation drafts for a task title + description.
 * Calls the Edge Function; throws on error so the caller can display a message.
 */
export async function generateTaskTranslations(
  sourceLang: SupportedLang,
  title: string,
  description: string
): Promise<TaskTranslationDraft> {
  const fields: { title: string; description?: string } = { title: title.trim() };
  if (description.trim()) fields.description = description.trim();

  const result = await callTranslateTextFunction({
    source_language: sourceLang,
    entity_type: "task",
    fields,
  });

  // Fall back to original source text if a field comes back empty
  const srcTitle = title.trim();
  const srcDesc  = description.trim();

  return {
    title_ru:       result.ru.title       ?? (sourceLang === "ru" ? srcTitle : ""),
    title_uz:       result.uz.title       ?? (sourceLang === "uz" ? srcTitle : ""),
    title_en:       result.en.title       ?? (sourceLang === "en" ? srcTitle : ""),
    description_ru: result.ru.description ?? (sourceLang === "ru" ? srcDesc  : ""),
    description_uz: result.uz.description ?? (sourceLang === "uz" ? srcDesc  : ""),
    description_en: result.en.description ?? (sourceLang === "en" ? srcDesc  : ""),
    status_ru: sourceLang === "ru" ? "original" : "auto_translated",
    status_uz: sourceLang === "uz" ? "original" : "auto_translated",
    status_en: sourceLang === "en" ? "original" : "auto_translated",
    providerConnected: true,
  };
}

export interface DocLinkTranslationDraft {
  title_ru: string;
  title_uz: string;
  title_en: string;
  description_ru: string;
  description_uz: string;
  description_en: string;
}

/**
 * Generate translation drafts for a doc link title + description.
 */
export async function generateDocLinkTranslations(
  sourceLang: SupportedLang,
  title: string,
  description: string
): Promise<DocLinkTranslationDraft> {
  const fields: { title: string; description?: string } = { title: title.trim() };
  if (description.trim()) fields.description = description.trim();

  const result = await callTranslateTextFunction({
    source_language: sourceLang,
    entity_type: "task",
    fields,
  });

  const srcTitle = title.trim();
  const srcDesc  = description.trim();

  return {
    title_ru:       result.ru.title       ?? (sourceLang === "ru" ? srcTitle : ""),
    title_uz:       result.uz.title       ?? (sourceLang === "uz" ? srcTitle : ""),
    title_en:       result.en.title       ?? (sourceLang === "en" ? srcTitle : ""),
    description_ru: result.ru.description ?? (sourceLang === "ru" ? srcDesc  : ""),
    description_uz: result.uz.description ?? (sourceLang === "uz" ? srcDesc  : ""),
    description_en: result.en.description ?? (sourceLang === "en" ? srcDesc  : ""),
  };
}

export interface AgendaTranslationDraft {
  title_ru: string;
  title_uz: string;
  title_en: string;
  presenter_ru: string;
  presenter_uz: string;
  presenter_en: string;
  status_ru: TranslationStatus;
  status_uz: TranslationStatus;
  status_en: TranslationStatus;
  providerConnected: boolean;
}

/**
 * Generate translation drafts for an agenda item title + presenter.
 * Calls the Edge Function; throws on error so the caller can display a message.
 */
export async function generateAgendaTranslations(
  sourceLang: SupportedLang,
  title: string,
  presenter: string
): Promise<AgendaTranslationDraft> {
  const fields: { title: string; presenter?: string } = { title: title.trim() };
  if (presenter.trim()) fields.presenter = presenter.trim();

  const result = await callTranslateTextFunction({
    source_language: sourceLang,
    entity_type: "agenda_item",
    fields,
  });

  const srcTitle = title.trim();
  const srcPresenter = presenter.trim();

  return {
    title_ru:     result.ru.title     ?? (sourceLang === "ru" ? srcTitle     : ""),
    title_uz:     result.uz.title     ?? (sourceLang === "uz" ? srcTitle     : ""),
    title_en:     result.en.title     ?? (sourceLang === "en" ? srcTitle     : ""),
    presenter_ru: result.ru.presenter ?? (sourceLang === "ru" ? srcPresenter : ""),
    presenter_uz: result.uz.presenter ?? (sourceLang === "uz" ? srcPresenter : ""),
    presenter_en: result.en.presenter ?? (sourceLang === "en" ? srcPresenter : ""),
    status_ru: sourceLang === "ru" ? "original" : "auto_translated",
    status_uz: sourceLang === "uz" ? "original" : "auto_translated",
    status_en: sourceLang === "en" ? "original" : "auto_translated",
    providerConnected: true,
  };
}

// ─── Profile translation ──────────────────────────────────────────────────────

export interface ProfileTranslationDraft {
  [key: string]: string;
}

/**
 * Translate multiple profile text fields from any source language to the other two.
 *
 * @param sourceLang — the language the user filled in ("ru", "en", or "uz")
 * @param fields — map of field keys (with suffix, e.g. "current_position_ru") to their values
 * @returns flat object with translations for the two target languages,
 *          e.g. { current_position_en: "...", current_position_uz: "..." }
 */
export async function generateProfileTranslations(
  sourceLang: SupportedLang,
  fields: Record<string, string>
): Promise<ProfileTranslationDraft> {
  const entries = Object.entries(fields).filter(([, v]) => v.trim());
  if (entries.length === 0) return {};

  // Combine all fields into one "description" for a single API call
  const DELIMITER = "\n===FIELD_SEPARATOR===\n";
  const combinedText = entries.map(([key, val]) => `[${key}]: ${val}`).join(DELIMITER);

  const { data: { session } } = await supabase.auth.getSession();
  if (!session) throw new Error("Not authenticated");

  const url = `${import.meta.env.VITE_SUPABASE_URL as string}/functions/v1/translate-text`;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${session.access_token}`,
      "apikey": supabaseAnonKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      source_language: sourceLang,
      entity_type: "task",
      fields: { description: combinedText },
    }),
  });

  const result = await res.json();
  if (!res.ok) throw new Error(result.error || `Translation error (HTTP ${res.status})`);

  // Determine target languages (the two that are NOT the source)
  const targetLangs = (["ru", "en", "uz"] as const).filter((l) => l !== sourceLang);
  const draft: ProfileTranslationDraft = {};

  const suffixFromSource = sourceLang === "uz" ? "uz" : sourceLang;

  for (const targetLang of targetLangs) {
    const translatedText = result[targetLang]?.description || "";

    for (const entry of entries) {
      const key = entry[0]; // e.g. "current_position_ru"
      // Strip source suffix to get base name
      const base = key.replace(new RegExp(`_${suffixFromSource}$`), "");
      const regex = new RegExp(`\\[${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\]:\\s*(.+?)(?=\\[|===FIELD_SEPARATOR===|$)`, "s");
      const match = translatedText.match(regex);
      if (match) {
        draft[`${base}_${targetLang}`] = match[1].trim();
      }
    }
  }

  return draft;
}

// ─── Notification translation ─────────────────────────────────────────────────

/**
 * Batch-translate notification titles and bodies to a target language.
 * Groups them into one API call using a delimiter trick.
 * Returns a map of notificationId → { title, body }.
 */
export async function translateNotificationTexts(
  items: { id: string; title: string; body: string }[],
  targetLang: "uz" | "en"
): Promise<Record<string, { title: string; body: string }>> {
  if (items.length === 0) return {};

  const { data: { session } } = await supabase.auth.getSession();
  if (!session) return {};

  // Use short indexed markers ([T0], [B0]) instead of UUIDs —
  // AI reliably preserves short alphanumeric tags during translation.
  const combined = items
    .map((n, i) => `[T${i}]: ${n.title}\n[B${i}]: ${n.body}`)
    .join("\n");

  const url = `${import.meta.env.VITE_SUPABASE_URL as string}/functions/v1/translate-text`;

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${session.access_token}`,
        "apikey": supabaseAnonKey,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        source_language: "ru",
        entity_type: "task",
        fields: { description: combined },
      }),
    });

    if (!res.ok) return {};
    const result = await res.json();
    const translatedText: string = result[targetLang]?.description || "";

    const out: Record<string, { title: string; body: string }> = {};
    for (let i = 0; i < items.length; i++) {
      // Stop capture at next [Tx] or [Bx] marker, or end of string
      const titleMatch = translatedText.match(
        new RegExp(`\\[T${i}\\]:\\s*(.+?)(?=\\n\\[|$)`, "s")
      );
      const bodyMatch = translatedText.match(
        new RegExp(`\\[B${i}\\]:\\s*(.+?)(?=\\n\\[|$)`, "s")
      );
      out[items[i].id] = {
        title: titleMatch?.[1]?.trim() || items[i].title,
        body:  bodyMatch?.[1]?.trim()  || items[i].body,
      };
    }
    return out;
  } catch {
    return {};
  }
}

// ─── UI helpers ───────────────────────────────────────────────────────────────

/** Human-readable dot/symbol for a translation status */
export function translationStatusLabel(status: TranslationStatus): string {
  switch (status) {
    case "original":        return "●";
    case "auto_translated": return "✦";
    case "reviewed":        return "✓";
    case "missing":         return "○";
  }
}

/** Colour for a translation status indicator */
export function translationStatusColor(status: TranslationStatus): string {
  switch (status) {
    case "original":        return "#059669"; // green
    case "auto_translated": return "#7C3AED"; // purple
    case "reviewed":        return "#2563EB"; // blue
    case "missing":         return "#D1D5DB"; // gray
  }
}
